name: GitHub Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!!"
  super_test_job:
    runs-on: ubuntu-latest
    steps:
      - run: ls
  super_curl_job:
    runs-on: ubuntu-latest
    steps:
      - run: curl http://example.com
  super_multiple_job:
    runs-on: ubuntu-latest
    steps:
      - run: curl http://example.com
      - run: node -v
      - run: npx -v
