name: GitHub Actions Demo

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: リポジトリを取得する
        uses: actions/checkout@v4

      - name: danger JSの実行
        uses: danger/danger-js@12.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
